services:

  schemacrawler-mcpserver:
    image: schemacrawler/schemacrawler-ai:latest
    container_name: schemacrawler-mcpserver
    stdin_open: true
    tty: true
    environment:
    # See https://www.schemacrawler.com/database-support.html
    # for connecting to other databases
      # (put these in your .env file)
      SCHCRWLR_SERVER: sqlite
      SCHCRWLR_DATABASE: sc.db
      SCHCRWLR_INFO_LEVEL: maximum
      SCHCRWLR_LOG_LEVEL: INFO
      SCHCRWLR_MCP_SERVER_TRANSPORT: http
      # Set the server port
      SERVER_PORT: 9191   # Set the container port
    ports:
      - target: 9191      # The container port
        published: 9292   # The host port
    volumes:
    - type: bind
      source: ./
      target: /home/schcrwlr/share
