services:

  schemacrawler-mcpserver:
    image: schemacrawler/schemacrawler-ai:latest
    container_name: schemacrawler-mcpserver
    stdin_open: true
    tty: true
    ports:
    - "8080:8080"
    volumes:
    - type: bind
      source: ./
      target: /home/schcrwlr/share
    entrypoint: [ '/opt/schemacrawler/bin/schemacrawler.sh' ]
    command: >
      --server sqlite
      --database sc.db
      --command mcpserver
      --transport sse
      --info-level maximum
      --log-level INFO
    # See https://www.schemacrawler.com/database-support.html for connecting to other databases
