services:

  adventureworks:
    image: chriseaton/adventureworks:postgres
    container_name: adventureworks
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      # (put these in your .env file)
      POSTGRES_USER: ${SCHCRWLR_DATABASE_USER}
      POSTGRES_PASSWORD: ${SCHCRWLR_DATABASE_PASSWORD}

  schemacrawler-mcpserver:
    image: schemacrawler/schemacrawler-ai:latest
    container_name: schemacrawler-mcpserver
    stdin_open: true
    tty: true
    depends_on:
      - adventureworks
    environment:
    # See https://www.schemacrawler.com/database-support.html
    # for connecting to other databases
      # (put these in your .env file)
      SCHCRWLR_DATABASE_USER: ${SCHCRWLR_DATABASE_USER}
      SCHCRWLR_DATABASE_PASSWORD: ${SCHCRWLR_DATABASE_PASSWORD}
      SCHCRWLR_SERVER: postgresql
      SCHCRWLR_HOST: adventureworks
      SCHCRWLR_PORT: 5432
      SCHCRWLR_DATABASE: postgres
      SCHCRWLR_INFO_LEVEL: maximum
      SCHCRWLR_LOG_LEVEL: INFO
      SCHCRWLR_MCP_SERVER_TRANSPORT: sse
      # Set the server port
      SERVER_PORT: 9191   # Set the container port
    ports:
      - target: 9191      # The container port
        published: 9292   # The host port
    volumes:
    - type: bind
      source: ./
      target: /home/schcrwlr/share
