services:

  sakila:
    image: sakiladb/mysql
    container_name: sakila
    ports:
      - target: 3306      # The container port
        published: 3306   # The host port
        protocol: tcp
        mode: host

  schemacrawler-mcpserver:
    image: schemacrawler/schemacrawler-ai:latest
    container_name: schemacrawler-mcpserver
    stdin_open: true
    tty: true
    depends_on:
      - sakila
    environment:
    # See https://www.schemacrawler.com/database-support.html
    # for connecting to other databases
      # (put these in your .env file)
      SCHCRWLR_DATABASE_USER: ${SCHCRWLR_DATABASE_USER}
      SCHCRWLR_DATABASE_PASSWORD: ${SCHCRWLR_DATABASE_PASSWORD}
      SCHCRWLR_SERVER: mysql
      SCHCRWLR_HOST: sakila
      SCHCRWLR_PORT: 3306
      SCHCRWLR_DATABASE: sakila
      SCHCRWLR_INFO_LEVEL: maximum
      SCHCRWLR_LOG_LEVEL: INFO
      SCHCRWLR_MCP_SERVER_TRANSPORT: sse
      # Set the server port
      SERVER_PORT: 9191   # Set the container port
    ports:
      - target: 9191      # The container port
        published: 9292   # The host port
    volumes:
    - type: bind
      source: ./
      target: /home/schcrwlr/share
