services:

  adventureworks:
    image: chriseaton/adventureworks:postgres
    container_name: adventureworks
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    environment:
      # (put these in your .env file)
      POSTGRES_USER: ${SCHCRWLR_DATABASE_USER}
      POSTGRES_PASSWORD: ${SCHCRWLR_DATABASE_PASSWORD}

  schemacrawler-mcpserver:
    image: schemacrawler/schemacrawler-ai:latest
    container_name: schemacrawler-mcpserver
    stdin_open: true
    tty: true
    depends_on:
      - adventureworks
    environment:
      SERVER_PORT: 9191
      # (put these in your .env file)
      SCHCRWLR_DATABASE_USER: ${SCHCRWLR_DATABASE_USER}
      SCHCRWLR_DATABASE_PASSWORD: ${SCHCRWLR_DATABASE_PASSWORD}
    ports:
      - target: 9191      # The container port
        published: 9292   # The host port
    volumes:
    - type: bind
      source: ./
      target: /home/schcrwlr/share
    entrypoint: [ '/opt/schemacrawler/bin/schemacrawler.sh' ]
    command: >
      --server postgresql
      --host adventureworks
      --database postgres
      --user:env SCHCRWLR_DATABASE_USER
      --password:env SCHCRWLR_DATABASE_PASSWORD
      --routines .*
      --command mcpserver
      --transport sse
      --info-level maximum
      --log-level INFO
    # See https://www.schemacrawler.com/database-support.html for connecting to other databases
